### ISSUE TITLE
Problems due to amaranth when packaging a project with pyinstaller

### ISSUE THREAD

**Issue by chipmuenk** [amaranth-lang/amaranth#1549]
I'm using pyinstaller to provide self-extracting archives of https://github.com/chipmuenk/pyfda/ . When running the created binary, the attached error occurs. Perhaps you understand the error better than me. I'm also trying to find a solution from the pyinstaller side. Excluding amaranth from the build process yields a working binary.

```
C:\Users\sclif\Downloads>pyfdax_win.exe
Traceback (most recent call last):
  File "jschon\catalog\__init__.py", line 46, in __call__
  File "jschon\utils.py", line 48, in json_loadf
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sclif\\AppData\\Local\\Temp\\_MEI207842\\jschon\\catalog\\json-schema-2020-12\\schema.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyfda\pyfdax.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "pyfda\pyfda_rc.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "pyfda\libs\pyfda_lib.py", line 114, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "amaranth\__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "amaranth\hdl\__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "amaranth\hdl\_rec.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "amaranth\lib\wiring.py", line 1725, in <module>
  File "abc.py", line 106, in __new__
  File "amaranth\lib\meta.py", line 64, in __init_subclass__
  File "amaranth\lib\meta.py", line 37, in __jschon_schema
  File "jschon\__init__.py", line 49, in create_catalog
  File "jschon\catalog\_2020_12.py", line 103, in initialize
  File "jschon\catalog\__init__.py", line 215, in create_metaschema
  File "jschon\catalog\__init__.py", line 158, in load_json
  File "jschon\catalog\__init__.py", line 53, in __call__
jschon.exc.CatalogError: No such file or directory: 'C:\\Users\\sclif\\AppData\\Local\\Temp\\_MEI207842\\jschon\\catalog\\json-schema-2020-12\\schema.json'
[PYI-19192:ERROR] Failed to execute script 'pyfdax' due to unhandled exception!
```

**Comment by chipmuenk** [comment]
Thanks for the idea and the link - I added a little script to my pyinstaller spec file that adds all the json files (command options cannot be combined with spec files), see https://github.com/chipmuenk/pyfda/issues/258 . Unfortunately, amaranth still doesn't play nice with my installer script, the application starts but I get a quite generic warning 

    Error during import of "pyfda.fixpoint_widgets.fir_df.fir_df_amaranth_ui":
    invalid literal for int() with base 10: 'unknown'

Using the pyinstaller files with amaranth probably is a rare combination anyway, so I'll just exclude amaranth from the pyinstaller build script. ```pip install pyfda`` still includes amaranth.
