### ISSUE TITLE
Building tutorial code fails with type error

### ISSUE THREAD

**Issue by ChuckM** [amaranth-lang/amaranth#844]
[tmp.zip](https://github.com/amaranth-lang/amaranth/files/12114464/tmp.zip)

Error log
```
(quarterhorse) cmcmanis@quarterhorse:test-amaranth$ python counter-sim.py 
Traceback (most recent call last):
  File "/freenas/home/cmcmanis/arm-experiments/projects/test-amaranth/counter-sim.py", line 34, in <module>
    with sim.write_vcd("up_counter.vcd"):
  File "/home/cmcmanis/.local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/freenas/home/cmcmanis/arm-experiments/projects/amaranth/quarterhorse/lib/python3.11/site-packages/amaranth/sim/pysim.py", line 329, in write_vcd
    vcd_writer = _VCDWriter(self._fragment,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freenas/home/cmcmanis/arm-experiments/projects/amaranth/quarterhorse/lib/python3.11/site-packages/amaranth/sim/pysim.py", line 94, in __init__
    if re.search(r"[ \t\r\n]", var_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmcmanis/.local/lib/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
(quarterhorse) cmcmanis@quarterhorse:test-amaranth$
```
Not sure what is going on here yet, typed in code from the tutorial pages.

**Comment by ChuckM** [comment]
Foundational issue was apparently missing ctypes in the Python 3.11 install. Once I did the `apt install libffi-dev`, rebuilt python 3.11 (`.configure <opts> ; make; make install`). And then re-installed amaranth `pip3 install --editable amaranth` the example code I posted in this issue runs without complaint.
