### ISSUE TITLE
Transparent memory using Python simulator reading from incorrect address when write occurred on previous cycle also

### ISSUE THREAD

**Issue by cr1901** [amaranth-lang/amaranth#930]
Consider the following MCVE of a dual-port memory with a read port with `transparent=True`. The simulation reads from address 1:

```python
from amaranth import Module, Memory
from amaranth.lib.wiring import Component, In, Out
from amaranth.sim import Simulator


class TransMem(Component):
    rd_en: Out(1)
    wr_en: Out(1)
    adr_r: Out(5)
    adr_w: Out(5)
    dat_r: In(32)
    dat_w: Out(32)

    def __init__(self):
        super().__init__()
        self.mem = Memory(width=32, depth=32, init=[0, 8, 0])

    def elaborate(self, platform):
        m = Module()

        m.submodules.rdport = rdport = self.mem.read_port(transparent=True)
        m.submodules.wrport = wrport = self.mem.write_port()

        m.d.comb += [
            rdport.en.eq(self.rd_en),
            wrport.en.eq(self.wr_en),
            rdport.addr.eq(self.adr_r),
            wrport.addr.eq(self.adr_w),
            self.dat_r.eq(rdport.data),
            wrport.data.eq(self.dat_w),
        ]

        return m


def test_transparent_mem():
    trans_mem = TransMem()

    def testbench():
        yield trans_mem.adr_r.eq(1)
        yield trans_mem.adr_w.eq(2)
        yield trans_mem.dat_w.eq(0xfffff801)
        yield trans_mem.wr_en.eq(1)
        yield trans_mem.rd_en.eq(1)
        yield

        assert (yield trans_mem.dat_r) == 8

    sim = Simulator(trans_mem)
    sim.add_clock(period=1e-2)
    sim.add_sync_process(testbench)

    with sim.write_vcd("trans_mem.vcd", "trans_mem.gtkw"):
        sim.run()


if __name__ == "__main__":
    test_transparent_mem()
```

The simulation as of c7da6c1292ea fails with the following error:

```
William@DESKTOP-3H1DSBV MINGW64 ~/Projects/MCVE/amaranth-transparent
$ python transparent.py
Traceback (most recent call last):
  File "C:/msys64/home/William/Projects/MCVE/amaranth-transparent/transparent.py", line 58, in <module>
    test_transparent_mem()
  File "C:/msys64/home/William/Projects/MCVE/amaranth-transparent/transparent.py", line 54, in test_transparent_mem
    sim.run()
  File "C:/msys64/mingw64/lib/python3.11/site-packages/amaranth/sim/core.py", line 172, in run
    while self.advance():
          ^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/site-packages/amaranth/sim/core.py", line 163, in advance
    return self._engine.advance()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/site-packages/amaranth/sim/pysim.py", line 319, in advance
    self._step()
  File "C:/msys64/mingw64/lib/python3.11/site-packages/amaranth/sim/pysim.py", line 308, in _step
    process.run()
  File "C:/msys64/mingw64/lib/python3.11/site-packages/amaranth/sim/_pycoro.py", line 125, in run
    self.coroutine.throw(exn)
  File "C:/msys64/mingw64/lib/python3.11/site-packages/amaranth/sim/_pycoro.py", line 64, in run
    command = self.coroutine.send(response)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/site-packages/amaranth/sim/core.py", line 91, in wrapper
    yield from process()
  File "C:/msys64/home/William/Projects/MCVE/amaranth-transparent/transparent.py", line 47, in testbench
    assert (yield trans_mem.dat_r) == 8
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

A GTKWave trace suggests that the memory simulation is reading from address 2 instead of 1:
![image](https://github.com/amaranth-lang/amaranth/assets/6418027/5ed4f1b3-65ba-4496-b590-f52f7d531bf4)

If the line `yield trans_mem.wr_en.eq(1)` is commented out, the assertion `assert (yield trans_mem.dat_r) == 8` still fails. _However_, commenting out the assertion and then running the script again produces a trace where the correct address `1` is read after the `yield`/clock tick:

![image](https://github.com/amaranth-lang/amaranth/assets/6418027/2146e520-caf9-488d-9e9d-43fe36534498)

**Comment by wanda-phi** [comment]
The testbench is wrong, as it is missing `yield Settle()` before the assert.  With that change, it passes on current main.  The VCD trace shows a real problem, but it has been fixed in #923, so the VCD is presumably stale.
